### PR TITLE
Add a button for copying an asset from a remote server or deleting assets in the origin.

### PR DESCRIPTION
**Pull request by nrn**
Pairing w/ @wardcunningham on this

This is still less than half finished, hard coding 
http://localhost:3000/scad.fed.wiki/solid-cad-designs/view/candle-tilt
as our test case.

### CODE REVIEW

**Comment by WardCunningham** [comment]
image

Have yet to connect these buttons to the copy logic @nrn wrote. My click handler isn't listening until after the async fetch and render completes.

**Comment by WardCunningham** [comment]
image

If it doesn't make sense to offer fork because it is already your site, then it does make sense to offer delete because you may have forked or uploaded something you don't actually want. 

The retrieved urls are distinctly different as would be expected.
```
copy //scad.fed.wiki/assets/pages/candle-tilt/IMG_3804.JPG
copy //scad.fed.wiki/assets/pages/candle-tilt/candle-base.scad
copy //scad.fed.wiki/assets/pages/candle-tilt/candle-base.stl
delete /assets/pages/candle-tilt/IMG_3804.JPG
```

**Comment by nrn** [comment]
Looking good so far, is the next step wiring up the buttons to the ajax calls?

**Comment by WardCunningham** [comment]
Yes, I have to move stuff around so that $item and item are available when the fetch completes.

**Comment by WardCunningham** [comment]
I have my edits committed and pushed.

Still more to do:

- [x] solve copy data corruption problem
- [x] code delete handler server-side
- [x] code delete handler client-side
- [x] show buttons only when logged in to origin
- [x] report errors on failures

Some future pull request will consider adding an endpoint that resolves "collaborative assets".

**Comment by WardCunningham** [comment]
I've explored fork data corruption by retrieving the remote files by scp for reference and then comparing them ref vs loc with various unix tools. From this it seems text files are copied faithfully but not so binary files. Recall we are uploading binary files without issue. So I suspect some problem fetching or translating the fetched result.

First I ask `file` to describe the files:
```
ref/IMG_3804.JPG: JPEG image data, EXIF standard 2.21
loc/IMG_3804.JPG: data

ref/candle-base.scad: ASCII text
loc/candle-base.scad: ASCII text

ref/candle-base.stl: ASCII text
loc/candle-base.stl: ASCII text

ref/melted-candle.key: Zip archive data, at least v2.0 to extract
loc/melted-candle.key: Zip archive data, at least v2.0 to extract
```
I compare file lengths with `ls -l`:
```
-rw-r--r--  1 ward  staff   885311 Jul  3 06:21 ref/IMG_3804.JPG
-rw-r--r--  1 root  staff  1620515 Jul  3 06:35 loc/IMG_3804.JPG

-rw-r--r--  1 ward  staff      255 Jul  3 06:21 ref/candle-base.scad
-rw-r--r--  1 root  staff      255 Jul  3 06:37 loc/candle-base.scad

-rw-r--r--  1 ward  staff    28100 Jul  3 06:21 ref/candle-base.stl
-rw-r--r--  1 root  staff    28100 Jul  3 06:41 loc/candle-base.stl

-rw-r--r--  1 ward  staff  1476901 Jul  3 06:21 ref/melted-candle.key
-rw-r--r--  1 root  staff  2662659 Jul  3 06:42 loc/melted-candle.key
```
Then I dump some content with `od -x -N 128`:
```
ref/IMG_3804.JPG
0000000      d8ff    e1ff    fe0f    7845    6669    0000    4d4d    2a00
0000020      0000    0800    0b00    0f01    0200    0000    0600    0000
0000040      9200    1001    0200    0000    0a00    0000    9800    1201
0000060      0300    0000    0100    0600    0000    1a01    0500    0000
0000100      0100    0000    a200    1b01    0500    0000    0100    0000
0000120      aa00    2801    0300    0000    0100    0200    0000    3101
0000140      0200    0000    0700    0000    b200    3201    0200    0000
0000160      1400    0000    ba00    1302    0300    0000    0100    0100
0000200
loc/IMG_3804.JPG
0000000      bfef    efbd    bdbf    bfef    efbd    bdbf    ef0f    bdbf
0000020      7845    6669    0000    4d4d    2a00    0000    0800    0b00
0000040      0f01    0200    0000    0600    0000    ef00    bdbf    1001
0000060      0200    0000    0a00    0000    ef00    bdbf    1201    0300
0000100      0000    0100    0600    0000    1a01    0500    0000    0100
0000120      0000    ef00    bdbf    1b01    0500    0000    0100    0000
0000140      ef00    bdbf    2801    0300    0000    0100    0200    0000
0000160      3101    0200    0000    0700    0000    ef00    bdbf    3201
0000200

ref/candle-base.scad
0000000      6964    6666    7265    6e65    6563    2928    7b20    740a
0000020      6172    736e    616c    6574    5b28    2c30    2c30    352d
0000040      295d    200a    6320    6c79    6e69    6564    2872    3033
0000060      642c    373d    2930    0a3b    6e69    6574    7372    6365
0000100      6974    6e6f    2928    7b20    720a    746f    7461    2865
0000120      305b    332c    3133    312d    362e    302c    295d    200a
0000140      7320    6163    656c    5b28    2e31    2c32    2c31    5d31
0000160      0a29    2020    2020    7963    696c    646e    7265    3628
0000200
loc/candle-base.scad
0000000      6964    6666    7265    6e65    6563    2928    7b20    740a
0000020      6172    736e    616c    6574    5b28    2c30    2c30    352d
0000040      295d    200a    6320    6c79    6e69    6564    2872    3033
0000060      642c    373d    2930    0a3b    6e69    6574    7372    6365
0000100      6974    6e6f    2928    7b20    720a    746f    7461    2865
0000120      305b    332c    3133    312d    362e    302c    295d    200a
0000140      7320    6163    656c    5b28    2e31    2c32    2c31    5d31
0000160      0a29    2020    2020    7963    696c    646e    7265    3628
0000200

ref/candle-base.stl
0000000      6f73    696c    2064    704f    6e65    4353    4441    4d5f
0000020      646f    6c65    200a    6620    6361    7465    6e20    726f
0000040      616d    206c    302d    352e    3930    3430    2031    2e35
0000060      3636    3834    6537    302d    2038    2e30    3638    3730
0000100      3234    200a    2020    6f20    7475    7265    6c20    6f6f
0000120      0a70    2020    2020    2020    6576    7472    7865    3120
0000140      342e    3938    3137    2d65    3730    2d20    3832    382e
0000160      3634    2032    332d    372e    3438    3934    2d65    3730
0000200
loc/candle-base.stl
0000000      6f73    696c    2064    704f    6e65    4353    4441    4d5f
0000020      646f    6c65    200a    6620    6361    7465    6e20    726f
0000040      616d    206c    302d    352e    3930    3430    2031    2e35
0000060      3636    3834    6537    302d    2038    2e30    3638    3730
0000100      3234    200a    2020    6f20    7475    7265    6c20    6f6f
0000120      0a70    2020    2020    2020    6576    7472    7865    3120
0000140      342e    3938    3137    2d65    3730    2d20    3832    382e
0000160      3634    2032    332d    372e    3438    3934    2d65    3730
0000200

ref/melted-candle.key
0000000      4b50    0403    0014    0000    0000    4a0b    4ed3    aae1
0000020      e8ee    1107    0000    1107    0000    0012    0000    6e49
0000040      6564    2f78    6f44    7563    656d    746e    692e    6177
0000060      0300    0011    31b7    69f0    081b    1201    0817    1201
0000100      0103    0500    4418    0c2a    12fc    12fd    12fe    12fb
0000120      12fa    16cf    0312    fe08    1a12    0a3d    3a05    0803
0000140      12fa    021a    6e65    0322    fb08    2a12    0803    16cf
0000160      0332    fd08    3a12    0803    12fc    0040    1a4a    7041
0000200
loc/melted-candle.key
0000000      4b50    0403    0014    0000    0000    4a0b    bfef    4ebd
0000020      bfef    efbd    bdbf    bfef    07bd    0011    0700    0011
0000040      1200    0000    4900    646e    7865    442f    636f    6d75
0000060      6e65    2e74    7769    0061    1103    ef00    bdbf    ef31
0000100      bdbf    1b69    0108    1712    0108    0312    0001    1805
0000120      2a44    ef0c    bdbf    ef12    bdbf    ef12    bdbf    ef12
0000140      bdbf    ef12    bdbf    ef12    bdbf    1216    0803    bfef
0000160      12bd    3d1a    050a    033a    ef08    bdbf    1a12    6502
0000200
```

**Comment by WardCunningham** [comment]
I've added some more console logging wherein I find that text files are reported as their actual length but binary files appear shorter, perhaps as a count of code points or something else weird. Results inserted into the report above.

**Comment by nrn** [comment]
I couldn't find an easy solution using $.ajax without workarounds, but the fetch solution seems clean and works on all of our test files.

**Comment by WardCunningham** [comment]
Excellent. It never occured to me that these two operations might be fundamentally different on the inside and that a bit of mixing new with old could make things better. I've checked off this item in the todo list without even trying it. (But I will try it.)

**Review by paul90 — APPROVED** [review]
Looks good.

**Comment by paul90** [comment]
Published as + wiki-plugin-assets@0.2.4

**Pull request merged**
