### PR TITLE
use wiki site adapter for URL creation

### PR DESCRIPTION
**Pull request by paul90**
~~**NOT FOR MERGING YET**~~
This code depends on some changes in wiki-client (site adapters getURL), and wiki-server (to add support for proxy access to assets).

### CODE REVIEW

**Comment by WardCunningham** [comment]
Thanks for posting this. I'll get a cleaner mege with the "collaborative link" logic I'm working on now. 

I wonder, since we're touching site adapter anyway, could this logic be turned into some simple boolean query of the revised site adapter?
```
wiki.site(requestSite).getURL('assets').startsWith('/proxy')
```

**Comment by paul90** [comment]
I am thinking we need to differentiate between the `getURL` call that are needed within the client, and those that are needed to create links that will be used externally. Think this needs the addition of a `getDirectURL` - there is only any difference between the two calls when the origin is using TLS and the target of the link is not.

**Comment by WardCunningham** [comment]
That makes sense. More aligned with purpose.

There is only a difference between the two calls because browser's handle img src differently than js fetch.

**Comment by WardCunningham** [comment]
Looks pretty simple when it all gets merged.

**Review by paul90 — COMMENTED** [review]
This change provides a fix for #7

**Comment by paul90** [comment]
I think this, together with the associated PRs fedwiki/wiki-server#138, and fedwiki/wiki-client#214 are ready for merging.

**Comment by paul90** [comment]
Had forgotten to commit one using the call to getDirectURL for the links. Also added some string interpolation to remove the extra `/` in the link

**Pull request merged**
